# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ev1ZG3U_05UCOGyITdSgg3b50NKqet_S
"""

import pandas as pd



df = pd.read_csv("/Netflix Datasets Evaluation MS Excel.csv")

import ipywidgets as widgets
from IPython.display import display

# Replace missing countries with "Unknown"
df["rating"] = df["rating"].fillna("Unknown")

# Create country dropdown

rating_dropdown = widgets.Dropdown(
    options=["All"] + sorted(df["rating"].unique().tolist()),
    value="All",
    description="Rating:"
)

# Output widget
output = widgets.Output()

# Update function
def update_table(change):
    with output:
        output.clear_output()
        if rating_dropdown.value == "All":
            display(df[["title", "type", "country", "release_year", "rating", "listed_in"]])
        else:
            filtered = df[df["rating"] == rating_dropdown.value]
            display(filtered[["title", "type", "country", "release_year", "rating", "listed_in"]])

# Link function to dropdown
rating_dropdown.observe(update_table, names="value")

# Display widgets
display(rating_dropdown, output)
update_table(None)